language: php
sudo: required
php:
    - 7.1
    - 7.2
    - 7.3
    - 7.4
    - 8.0
install:
    - composer install
script:
    - php vendor/bin/phpcbf -p
    - php vendor/bin/phpstan analyse -c phpstan.neon -l max src
jobs:
    allow_failures:
        - php: 8.0